#! /bin/sh 
setbg & 
picom & 
dunst & 
sxhkdl &
dbusfm &
BCD &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pulsemeeter init &
xhost SI:localuser:games & # allow games user to acces display

#xss-lock -- termlockscreen start +resetsaver &
xrdb $XDG_CONFIG_HOME/x11/Xresources
xset r rate 300 50 
xset s 600 
