#!/bin/sh

hyprlock
waygtk & 
hyprctl setcursor Vimix 16 &
swayidle -w &
xhost SI:localuser:games
pulsemeeter init &
dbusfm &
hyprpaper -c ~/.config/colorfig/generated/hyprpaper.conf &
dunst &
waybar &
