#! /bin/sh

. $HOME/.config/colorfig/generated/colors.sh 


#### Program Launch ####
pidof polybar || polyLaunch &
xsetroot -cursor_name left_ptr & # Remove X cursor


####### Mouse #######
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true 
bspc config pointer_follows_focus false


##### Monitors #####
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9 10 
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10 


####### Gaps ########
bspc config border_width	2
bspc config window_gap		20 
bspc config top_padding		25 
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0


###### Border ######
bspc config normal_border_color $background
bspc config active_border_color $background
bspc config focused_border_color $main
bspc config presel_feedback_color $main


## Window settings ##
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config removal_adjustment true
bspc config initial_polarity first_child
bspc config automatic_scheme spiral

####### Rules #######
bspc rule -a screenlock state=fullscreen
bspc rule -a screenlock sticky=on
bspc rule -a calendar border=off
#bspc rule -a Pulsemeeter border=off
bspc rule -a calendar state=floating
bspc rule -a scratchpad state=floating
bspc rule -a scratchpad border=off
bspc rule -a gui-Main state=floating # jflap
bspc rule -a Zathura state=tiled
bspc rule -a theme_prompt state=floating

bspc rule -a whatsapp-nativefier-d40211 desktop='^2' # wpp
bspc rule -a discord desktop='^2' # wpp

bspc rule -a overwatch.exe desktop='^10' #overwatch
bspc rule -a battle.net.exe desktop='^10' #battle.net
bspc rule -a dontstarve_steam desktop='^10' #dont starve together
bspc rule -a darksoulsremastered.exe desktop='^10' #dark souls remastered
bspc rule -a steam_app_292030 desktop='^10' #witcher 3
bspc rule -a Terraria.bin.x86_64 desktop='^10' #terraria
bspc rule -a steam_app_945360 desktop='^10' #among us
bspc rule -a steam_app_304050 desktop='^10' #trove
bspc rule -a darksoulsii.exe desktop='^10' #dark souls 2
bspc rule -a steam_app_880940 desktop='^10' #pummel party
bspc rule -a sekiro.exe desktop='^10' #sekiro
bspc rule -a steam_app_289070 desktop='^10' #civ vi
bspc rule -a hollow_knight.x86_64 desktop='^10' #hollow_knight
bspc rule -a deadcells desktop='^10' #dead cells
